version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:16  # Docker-образ для Node.js 16
    steps:
      - checkout               # Клонування репозиторію
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test:api

workflows:
  version: 2
  build_and_test:
    jobs:
      - test